# Generated by Django 3.2.7 on 2021-09-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transform_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name': 'file', 'verbose_name_plural': 'files'},
        ),
        migrations.RemoveField(
            model_name='videos',
            name='video',
        ),
        migrations.AddField(
            model_name='videos',
            name='file',
            field=models.FileField(default=None, upload_to='files/'),
        ),
    ]
