# Generated by Django 3.2.7 on 2021-09-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transform_page', '0002_auto_20210922_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='file',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
