# Generated by Django 3.2.7 on 2021-10-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transform_page', '0003_alter_videos_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideosLogosTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('dictionary_of_values', models.CharField(max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='videos',
            name='file',
            field=models.FileField(default=None, upload_to='file'),
        ),
    ]
